apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-aliases
  namespace: kube-system
data:
  registryAliases: example.org example.com test.com test.org registry.minikube registry.kube-system
  registrySvc: registry.kube-system.svc.cluster.local
