apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: kaniko
spec:
  podSelector:
    matchLabels:
      app: kaniko
  ingress: []
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              kubernetes.io/minikube-addons: registry
          ports:
            - port: 80
